name: Deploy TMLs to migration

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        description: "Select deploy type"
        required: true
        type: choice
        options:
          - DELTA
          - FULL

      deploy_policy:
        description: "Select deploy policy"
        required: true
        type: choice
        options:
          - ALL_OR_NONE
          - PARTIAL

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run deploy script
      - name: Run deploy
        env:
          DEPLOY_TYPE: ${{ github.event.inputs.deploy_type }}
          DEPLOY_POLICY: ${{ github.event.inputs.deploy_policy }}
        run: |
          python migration-deploy.py
