name: Deploy TMLs to Perft

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        description: "Select deploy type"
        required: true
        type: choice
        options:
          - DELTA
          - FULL

      deploy_policy:
        description: "Select deploy policy"
        required: true
        type: choice
        options:
          - ALL_OR_NONE
          - PARTIAL

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run deploy
        env:
          DEPLOY_TYPE: ${{ github.event.inputs.deploy_type }}
          DEPLOY_POLICY: ${{ github.event.inputs.deploy_policy }}
        run: |
          python perft-deploy.py
